[package]
name = "damasc-lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = "1.8.0"
itertools = "0.12.1"
nom = "7.1.3"
nom-supreme = "0.8.0"
nom_locate = "4.1.0"
