[workspace]
resolver = "2"

members = [
    "damasc-lang",
    "damasc-cli",
    "damasc-query",
    "damasc-repl",
    "damasc-wasm",
    "damasc-http",
    "damasc-join", 
    "damasc-grammar",
]

[profile.release]
opt-level = 3
strip = "debuginfo"
