[package]
name = "damasc-query"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
damasc-lang = { path = "../damasc-lang" }
itertools = "0.10.5"
nom = "7.1.3"
